version: "3.9"

services:
  backend:
    build: ./backend
    container_name: jobportal-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    networks:
      - app-net

  frontend:
    build: ./frontend
    container_name: jobportal-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
